import pandas as pd
import os 
# current_dir = os.getcwd()
root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# print(current_dir)
print(root_dir)

age_details = pd.read_csv(root_dir + '/Datasets/AgeGroupDetails (1).csv')
india_covid_19 = pd.read_csv(root_dir + '/Datasets/covid_19_india.csv')
hospital_beds = pd.read_csv(root_dir + '/Datasets/HospitalBedsIndia.csv')
individual_details = pd.read_csv(root_dir + '/Datasets/IndividualDetails.csv')
ICMR_details = pd.read_csv(root_dir + '/Datasets/ICMRTestingDetails.csv')
ICMR_labs = pd.read_csv(root_dir + '/Datasets/ICMRTestingLabs.csv')
state_testing = pd.read_csv(root_dir + '/Datasets/StatewiseTestingDetails.csv')
population = pd.read_csv(root_dir + '/Datasets/population_india_census2011.csv')
world_population = pd.read_csv(root_dir + '/Datasets/population_by_country_2020.csv')
confirmed_df = pd.read_csv(root_dir + '/Datasets/time_series_covid19_confirmed_global.csv')
deaths_df = pd.read_csv(root_dir + '/Datasets/time_series_covid19_deaths_global.csv')
recovered_df = pd.read_csv(root_dir + '/Datasets/time_series_covid19_recovered_global.csv')
latest_data = pd.read_csv(root_dir + '/Datasets/04-04-2020.csv')
age_details = pd.read_csv(root_dir + '/Datasets/AgeGroupDetails (1).csv')
covid19India = pd.read_csv(root_dir + '/Datasets/covid_19_india.csv')
covid19India['Date'] = pd.to_datetime(covid19India['Date'],dayfirst = True)
ICMR_details['DateTime'] = pd.to_datetime(ICMR_details['DateTime'],dayfirst = True)
ICMR_details = ICMR_details.dropna(subset=['TotalSamplesTested', 'TotalPositiveCases'])
indiaCencus = pd.read_csv(root_dir + '/Datasets/population_india_census2011.csv')
stateDetails = pd.read_csv(root_dir + '/Datasets/StatewiseTestingDetails.csv')
covid_df=pd.read_csv(root_dir + '/Datasets/covid_19_india.csv')
print("From Config")
print(covid_df.head())
vaccine_df=pd.read_csv(root_dir + '/Datasets/covid_vaccine_statewise.csv')
